name: Release
on:
  pull_request:
    types: closed
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    if: |
      (github.event_name == 'workflow_dispatch') || (
        github.event.pull_request.merged && (
          contains(github.event.pull_request.labels.*.name, 'npm-patch') ||
          contains(github.event.pull_request.labels.*.name, 'npm-minor') ||
          contains(github.event.pull_request.labels.*.name, 'npm-major')
        )
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Node.js v24
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Setup git
        run: |
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.name "Flo Edelmann"
          git config user.email "florian-edelmann@online.de"
      - name: Bump patch version
        if: (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'npm-patch')) || inputs['version-bump'] == 'patch'
        run: npm version patch --force -m "Version %s"
      - name: Bump minor version
        if: (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'npm-minor')) || inputs['version-bump'] == 'minor'
        run: npm version minor --force -m "Version %s"
      - name: Bump major version
        if: (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'npm-major')) || inputs['version-bump'] == 'major'
        run: npm version major --force -m "Version %s"
      - name: Release new version
        run: |
          npm publish --access public --provenance
          git push gh-origin HEAD:main --tags
          VERSION_NUMBER=$(git tag --list | tail -n 1 | cut -d v -f 2)
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: v${{ env.VERSION_NUMBER }}
          release_name: Version ${{ env.VERSION_NUMBER }}
          body: |
            **NEW:**
            **FIXED:**
            **IMPROVED:**
            **META:**
            **BREAKING:**
          draft: true
          prerelease: false
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
